print("Hello World")
print("What is your name?")
Name= input()
print("It's nice to meet you " + Name)
print("How old are you?")
Age= input()
year = 2025 - int(Age)
print("Cool, then you were born in " + str(year))